#!/usr/bin/env python3
"""Generate SBOM.md from `cargo metadata` — the shipped binary's supply chain.

Classification (host-context propagation):
* runtime      — reached only through normal edges of normal crates:
                 compiled into / linked by the binary
* build-time   — proc-macro crates, their dependency closure, and anything
                 reached through a `build` (build-script) edge: executes on
                 the build host, NOT linked into the shipped binary
* dev-only     — closure of the root's dev-dependencies, minus the above
Run from the repo root:  python3 scripts/sbom.py > SBOM.md
"""
import json
import subprocess
import sys

meta = json.loads(subprocess.run(
    ["cargo", "metadata", "--format-version", "1"],
    capture_output=True, text=True, check=True).stdout)
pkgs = {p["id"]: p for p in meta["packages"]}
resolve = {n["id"]: n for n in meta["resolve"]["nodes"]}
root = next(p["id"] for p in meta["packages"] if p["name"] == "newgit")
by_name = {}
for p in meta["packages"]:
    by_name.setdefault(p["name"], p["id"])


def is_proc_macro(i):
    return any("proc-macro" in t.get("kind", []) for t in pkgs[i].get("targets", []))


def walk(start_ids, block_dev=True):
    """Return {id: 'runtime'|'build'} reached from start_ids via normal/build
    edges. A crate reached with host-context (through a proc-macro or a build
    edge) is build-time UNLESS some normal path also reaches it."""
    cls = {}
    stack = [(s, False) for s in start_ids]
    while stack:
        nid, host = stack.pop()
        prev = cls.get(nid)
        if nid not in start_ids:
            new = "build" if (host or is_proc_macro(nid)) else "runtime"
            if prev is None or (prev == "build" and new == "runtime"):
                cls[nid] = new
            elif prev == new:
                pass
            else:
                continue  # already classified with a stronger class
        elif prev is not None:
            continue
        else:
            cls[nid] = "root"
        node_host = host or (nid not in start_ids and is_proc_macro(nid))
        for d in resolve[nid]["deps"]:
            for k in (d.get("dep_kinds") or [{}]):
                kt = k.get("kind")
                if kt is None:
                    stack.append((d["pkg"], node_host))
                elif kt == "build":
                    stack.append((d["pkg"], True))
                # 'dev' edges: skipped when walking the shipped chain
    cls.pop(root, None)
    return cls


shipped = walk([root])
runtime = {i for i, c in shipped.items() if c == "runtime"}
buildtime = {i for i, c in shipped.items() if c == "build"}

direct = [(d["name"], d["req"], d.get("kind")) for d in pkgs[root]["dependencies"]]
dev_roots = [by_name[n] for n, _, k in direct if k == "dev"]
dev_all = walk(dev_roots, block_dev=False)
dev_only = {i for i in dev_all if i not in runtime and i not in buildtime} | set(dev_roots)
dev_only -= {root}


def rows(ids):
    seen, out = set(), []
    for i in sorted(ids, key=lambda x: (pkgs[x]["name"].lower(), pkgs[x]["version"])):
        key = (pkgs[i]["name"], pkgs[i]["version"])
        if key in seen:
            continue
        seen.add(key)
        out.append((key[0], key[1], pkgs[i]["license"] or "?",
                    (pkgs[i]["source"] or "local").replace("registry+", "")))
    return out


w = sys.stdout.write
w("""# NewGit SBOM — software bill of materials

Generated by `scripts/sbom.py` (cargo metadata) — deterministic output; CI
fails on drift via `python3 scripts/sbom.py | diff -u SBOM.md -`. Scope: the
**shipped binary's** supply chain, split by where each crate actually runs.
Dev-only crates (tests) cannot affect the shipped artifact and are listed
separately. Dependency budget policy: DECISIONS.md D-002. Lockfile:
Cargo.lock (committed; registry checksums).

## Direct dependencies (Cargo.toml)

| crate | req | class |
|---|---|---|
""")
for n, req, k in sorted(direct):
    w(f"| {n} | {req} | {'dev (tests only)' if k == 'dev' else 'runtime'} |\n")

w(f"""
## Runtime closure ({len(rows(runtime))} crates — compiled into / linked by the binary)

| crate | version | license | source |
|---|---|---|---|
""")
for n, v, lic, src in rows(runtime):
    w(f"| {n} | {v} | {lic} | {src} |\n")

w(f"""
## Build-time closure ({len(rows(buildtime))} crates — proc macros, their deps, and build-script helpers; execute on the build host, NOT linked into the binary)

| crate | version | license | source |
|---|---|---|---|
""")
for n, v, lic, src in rows(buildtime):
    w(f"| {n} | {v} | {lic} | {src} |\n")

w(f"""
## Dev-only closure ({len(rows(dev_only))} crates — tests/benches; never shipped)

{", ".join(f"{n} {v}" for n, v, _, _ in rows(dev_only)) or "(none)"}

## Policy notes

* **6 direct runtime dependency families** (flate2, getrandom, serde/serde_json,
  sha2, tempfile, thiserror; seven crate entries) — the D-002 budget. `getrandom`
  was already in the locked runtime closure through `tempfile` and is now a
  direct dependency for portable OS CSPRNG access (D-022). No git/path/patched
  sources: all crates.io.
* flate2 uses its **pure-Rust** backend (miniz_oxide) — no C/libz linkage;
  sha2 uses runtime CPU feature detection (cpufeatures), no bundled asm.
* `#![forbid(unsafe_code)]` covers newgit's own code; unsafe inside the
  closure is upstream's — tracked in THREAT_MODEL §G (supply chain).
* Licenses across all tables: MIT / Apache-2.0 / 0BSD / Zlib / Unlicense /
  Unicode-3.0 — all permissive, compatible with NewGit's
  `MIT OR Apache-2.0` dual license.
* Regenerate after ANY Cargo.toml/Cargo.lock change:
  `python3 scripts/sbom.py > SBOM.md`.
""")
